spring:
  profiles:
    include:
      - dev

---
#dev
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:h2:mem:mydb;DB_CLOSE_ON_EXIT=FALSE;MODE=PostgreSQL;INIT=CREATE SCHEMA IF NOT EXISTS test
    driver-class-name: org.h2.Driver
    username: sa
    initialization-mode: always

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    properties:
      show_sql: true
      format_sql: true

    hibernate:
      ddl-auto: create

  redis:
    host: 127.0.0.1
    port: 6379
